# Jekyll Configuration for Nomsa Ngwenya's CV

# Theme settings
remote_theme: pages-themes/midnight@v0.2.0

# Plugins (for GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title: "NG Ngwenya CV"
author: "Nomsa Ngwenya"
description: "Creative and goal-driven senior student of NWU with a passion for ICT."
email: nkululekongwenya123@gmail.com

# URL settings
url: "https://cyberkidleko.github.io"  # Your GitHub Pages URL
baseurl: "/cyberkidleko1.github.io"    # Your repository name

# Markdown processing
markdown: kramdown

# Permalinks
permalink: pretty

# Social media
social:
  github: CyberKidLeko

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
